# Generated by Django 2.1.2 on 2018-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_management', '0005_auto_20181020_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
