# Generated by Django 2.1.2 on 2018-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_management', '0006_auto_20181021_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
