# Generated by Django 2.1.2 on 2018-11-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt_management', '0007_receipt_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Salary', 'salary')], max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
